[2025-08-14T07:46:05.340+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-14T07:46:05.381+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_transform_pipeline.silver_topcv_transform manual__2025-08-14T07:46:01.998733+00:00 [queued]>
[2025-08-14T07:46:05.388+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_transform_pipeline.silver_topcv_transform manual__2025-08-14T07:46:01.998733+00:00 [queued]>
[2025-08-14T07:46:05.389+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-14T07:46:05.403+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): silver_topcv_transform> on 2025-08-14 07:46:01.998733+00:00
[2025-08-14T07:46:05.413+0000] {standard_task_runner.py:63} INFO - Started process 2943 to run task
[2025-08-14T07:46:05.416+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_transform_pipeline', 'silver_topcv_transform', 'manual__2025-08-14T07:46:01.998733+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/etl_jobs_dag.py', '--cfg-path', '/tmp/tmppzz656i1']
[2025-08-14T07:46:05.418+0000] {standard_task_runner.py:91} INFO - Job 169: Subtask silver_topcv_transform
[2025-08-14T07:46:05.483+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_transform_pipeline.silver_topcv_transform manual__2025-08-14T07:46:01.998733+00:00 [running]> on host ddcaa82da13c
[2025-08-14T07:46:05.581+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_transform_pipeline' AIRFLOW_CTX_TASK_ID='silver_topcv_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T07:46:01.998733+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-14T07:46:01.998733+00:00'
[2025-08-14T07:46:05.582+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-14T07:46:05.610+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-08-14T07:46:05.612+0000] {spark_submit.py:351} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.driver.extraClassPath=/opt/custom-jars/* --conf spark.executor.extraClassPath=/opt/custom-jars/* --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.AbstractFileSystem.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS --conf spark.hadoop.google.cloud.auth.service.account.enable=true --conf spark.hadoop.google.cloud.auth.service.account.json.keyfile=/opt/***/gcp-key.json --conf spark.pyspark.python=/opt/bitnami/python/bin/python3 --conf spark.pyspark.driver.python=/opt/bitnami/python/bin/python3 --conf spark.submit.deployMode=cluster --jars /opt/custom-jars/aws-java-sdk-bundle-1.12.262.jar,/opt/custom-jars/hadoop-aws-3.3.4.jar --name arrow-spark /opt/spark-jobs/transform/gold_transform.py
[2025-08-14T07:46:06.579+0000] {spark_submit.py:521} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-08-14T07:46:07.996+0000] {spark_submit.py:521} INFO - Exception in thread "main" org.apache.spark.SparkException: Cluster deploy mode is currently not supported for python applications on standalone clusters.
[2025-08-14T07:46:07.996+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.error(SparkSubmit.scala:1045)
[2025-08-14T07:46:07.997+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:301)
[2025-08-14T07:46:07.998+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:961)
[2025-08-14T07:46:07.998+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:204)
[2025-08-14T07:46:07.998+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:227)
[2025-08-14T07:46:07.999+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:96)
[2025-08-14T07:46:07.999+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1132)
[2025-08-14T07:46:07.999+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1141)
[2025-08-14T07:46:07.999+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-08-14T07:46:08.015+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-14T07:46:08.027+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.driver.extraClassPath=/opt/custom-jars/* --conf spark.executor.extraClassPath=/opt/custom-jars/* --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.AbstractFileSystem.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS --conf spark.hadoop.google.cloud.auth.service.account.enable=true --conf spark.hadoop.google.cloud.auth.service.account.json.keyfile=/opt/***/gcp-key.json --conf spark.pyspark.python=/opt/bitnami/python/bin/python3 --conf spark.pyspark.driver.python=/opt/bitnami/python/bin/python3 --conf spark.submit.deployMode=cluster --jars /opt/custom-jars/aws-java-sdk-bundle-1.12.262.jar,/opt/custom-jars/hadoop-aws-3.3.4.jar --name arrow-spark /opt/spark-jobs/transform/gold_transform.py. Error code is: 1.
[2025-08-14T07:46:08.032+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_transform_pipeline, task_id=silver_topcv_transform, run_id=manual__2025-08-14T07:46:01.998733+00:00, execution_date=20250814T074601, start_date=20250814T074605, end_date=20250814T074608
[2025-08-14T07:46:08.048+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 169 for task silver_topcv_transform (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.driver.extraClassPath=/opt/custom-jars/* --conf spark.executor.extraClassPath=/opt/custom-jars/* --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.AbstractFileSystem.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS --conf spark.hadoop.google.cloud.auth.service.account.enable=true --conf spark.hadoop.google.cloud.auth.service.account.json.keyfile=/opt/***/gcp-key.json --conf spark.pyspark.python=/opt/bitnami/python/bin/python3 --conf spark.pyspark.driver.python=/opt/bitnami/python/bin/python3 --conf spark.submit.deployMode=cluster --jars /opt/custom-jars/aws-java-sdk-bundle-1.12.262.jar,/opt/custom-jars/hadoop-aws-3.3.4.jar --name arrow-spark /opt/spark-jobs/transform/gold_transform.py. Error code is: 1.; 2943)
[2025-08-14T07:46:08.080+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-14T07:46:08.100+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T07:46:08.103+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
